# Generated by Django 4.2.1 on 2023-05-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerschedule',
            old_name='coach',
            new_name='trainer',
        ),
    ]
