# Generated by Django 4.2.1 on 2023-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_coach_trainerschedule_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerschedule',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name'),
        ),
    ]
