# Generated by Django 4.2.1 on 2023-06-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_trainerschedule_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='note',
            field=models.TextField(blank=True, help_text='Note about membership', null=True, verbose_name='Note'),
        ),
    ]
