# Generated by Django 4.2.1 on 2023-06-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_membershippayment_pool_duration'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='payments.membershippayment', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='membership_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='payments.paymenttype', verbose_name='Membership type'),
        ),
    ]
