# Generated by Django 4.2.1 on 2023-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_payment_alter_journal_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Create date'),
        ),
    ]
