# Generated by Django 4.2.1 on 2023-07-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
    ]
