# Generated by Django 4.2.1 on 2023-07-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='status',
        ),
    ]
