# Generated by Django 4.2.1 on 2023-06-01 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='pool_duration',
            field=models.TimeField(blank=True, default=datetime.time(1, 0), null=True, verbose_name='Pool duration'),
        ),
    ]
