# Generated by Django 4.2.1 on 2023-06-01 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_membershippayment_pool_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='pool_duration',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='Pool duration'),
        ),
    ]
