# Generated by Django 4.2.1 on 2023-07-13 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_membershippayment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date of the payment period'),
        ),
    ]
