# Generated by Django 4.2.1 on 2023-07-14 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymenttype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='pool_duration',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='Pool Duration'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='visits_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Visits Count'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='with_trainer',
            field=models.BooleanField(default=False, verbose_name='With Trainer'),
        ),
    ]
