# Generated by Django 4.2.1 on 2023-07-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_membershippayment_start_date'),
        ('payments', '0007_alter_paymenttype_period_and_more'),
    ]

    operations = [
    ]
