# Generated by Django 4.2.1 on 2023-07-24 10:04

from django.db import migrations, models
import utils.time


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_merge_20230719_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='start_date',
            field=models.DateField(default=utils.time.get_current_date, verbose_name='Start date of the payment period'),
        ),
    ]
