# Generated by Django 4.2.1 on 2023-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='history_type_icons/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'History type',
                'verbose_name_plural': 'History types',
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.membership', verbose_name='Membership')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='history.historytype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Membership history',
                'verbose_name_plural': 'Membership histories',
            },
        ),
    ]
