# Generated by Django 4.2.1 on 2023-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_historytype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytype',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='historytype',
            name='name',
            field=models.CharField(choices=[('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('refund', 'Refund'), ('payment', 'Payment')], max_length=255, verbose_name='Name'),
        ),
    ]
