# Generated by Django 4.2.1 on 2023-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnstileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_scan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key scan')),
                ('subscription_scan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription scan')),
                ('entry_time', models.DateTimeField(verbose_name='Entry time')),
                ('exit_time', models.DateTimeField(verbose_name='Exit time')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('status', models.BooleanField(choices=[('True', 'Вход'), ('False', 'Выход')], db_index=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pass history',
                'verbose_name_plural': 'Pass histories',
                'db_table': 'turnstile_history',
            },
        ),
    ]
