# Generated by Django 4.2.1 on 2023-07-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
        ('accounts', '0005_membership_note'),
        ('turnstile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnstilehistory',
            name='key_scan',
        ),
        migrations.RemoveField(
            model_name='turnstilehistory',
            name='subscription_scan',
        ),
        migrations.AddField(
            model_name='turnstilehistory',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pool.key', verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='turnstilehistory',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.membership', verbose_name='Membership'),
        ),
        migrations.AddField(
            model_name='turnstilehistory',
            name='service_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pool.servicecard', verbose_name='Service Card'),
        ),
    ]
