# Generated by Django 4.2.1 on 2023-07-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnstile', '0002_remove_turnstilehistory_key_scan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnstilehistory',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='turnstilehistory',
            name='exit_time',
        ),
    ]
